services:
  mlx_cuda12:
    build:
      context: .
      dockerfile: Dockerfile.cuda12
    image: mlx-cuda12:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # 필요 시 워크디렉토리/소스 마운트:
    # volumes:
    #   - ./:/work
    # working_dir: /work

  mlx_cuda13:
    build:
      context: .
      dockerfile: Dockerfile.cuda13
    image: mlx-cuda13:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
